# Github Actions configuration file
# Build ETCDMXTool for Windows
name: Build

on:
  push:
  pull_request:
  page_build:
  release:
    types:
      - created
      - edited
      - prereleased
      - released

jobs:
  job:
    name: build-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.qtver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        qtver: ['5.15.2']
        arch: [x86, x64]
        include:
          - os: windows-latest
            arch: x86
            qtarch: win32_msvc2019
          - os: windows-latest
            arch: x64
            qtarch: win64_msvc2019_64

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: ${{ matrix.qtver }}
        arch: ${{ matrix.qtarch }}
    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
    - name: Create Makefile
      run: qmake EtcDmxTool.pro
    - name: Run MakeFile
      run: nmake
    - name: Upload Artifact
      if: contains(matrix.arch, 'x86')
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          install/ETCDmxTool*.exe
          release/*.pdb 
    - name: Setup TMate Session (Failure Only)
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3